[Interface]
PrivateKey = <Add Server Private Key>
Address = 10.100.0.1/24
ListenPort = 51820

[Peer]
PublicKey =  <Add Public Key>
AllowedIPs = 10.100.0.2/32
PersistentKeepalive = 25

[Peer]
PublicKey = <Add Public Key>
AllowedIPs = 10.100.0.3/32
PersistentKeepalive = 25

